### Naive Bayes [Seminar]

**Note:**

> Please do not delete comments or lines of code.

> Please show your solution by writing the calculation procedure.

```

1. At the lecture you studied the naive Bayesian algorithm, now it's time to do practice. The most common use of the naive Bayesov algorithm is the classification of messages as spam or not.

You have a file `` "sample_messages" `` `with spam & non-spam (HAM) messages, download it to Pandas.Dataframe` `Data```` '.

In [1]:
import os
os.listdir()

['.config', 'sample_messages.txt', '.ipynb_checkpoints', 'sample_data']

In [2]:
#Начало вашего кода

import pandas as pd
data = pd.read_table('sample_messages.txt', names = ['status', 'message'])

#Конец вашего кода

data.head()

status                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('status').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('message').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['message'].value_counts()
    for x_label, grp in _df_2.groupby('status')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('status')
_ = plt.ylabel('message')

### Expected results:

![image.png](attachment:image.png)

2. Perform a research analysis of the data `` Data```` ', and answer the following questions:

* How many messages are there in the data? Assign the result of the variable `` all_Messages````.

*How much is ** spam ** messages in the data? Assign the result of a variable `` spam messages````.

*How much is ** HAM ** messages in the data? Assign the result of the variable `` HAM_MESSAGES``` '.

*What is the probability that the message will be ** spam **? Assign the result of the variable `` p_spam``` '.

*What is the likelihood that the message will be ** HAM **? Assign the result of the variable `` P_HAM``` '.

In [3]:
#Начало вашего кода
all_messages = data['message'].count()
spam_messages = data[data['status'] == 'spam']['status'].count()
ham_messages = data[data['status'] == 'ham']['status'].count()
p_spam = spam_messages / all_messages
p_ham = ham_messages / all_messages
#Конец вашего кода

In [4]:
print(f"всего сообщений: {all_messages}")
print(f"всего spam сообщений: {spam_messages}")
print(f"всего ham сообщений: {ham_messages}")
print(f"вероятность того, что сообщение будет spam: {p_spam*100:.2f}%")
print(f"вероятность того, что сообщение будет ham: {p_ham*100:.2f}%")

всего сообщений: 20
всего spam сообщений: 8
всего ham сообщений: 12
вероятность того, что сообщение будет spam: 40.00%
вероятность того, что сообщение будет ham: 60.00%


### Expected results:

```
всего сообщений: 20
всего spam сообщений: 8
всего ham сообщений: 12
вероятность того, что сообщение будет spam: 40.00%
вероятность того, что сообщение будет ham: 60.00%
```

3. You may encounter the problem that messages have a different format and contain punctuation marks (which we can ignore). You must clean the data in this task.

In [11]:
import re
clean_data = data.copy()
#Начало вашего кода
clean_data['message'] = clean_data['message'].apply(
    lambda x: re.sub(r'[^\w\s]', '', str(x)).lower().strip()
)
#Конец вашего кода
for i in range(len(clean_data)):
    print(f"{i}\t{clean_data['message'][i]}")

0	go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat
1	ok lar joking wif u oni
2	free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s
3	u dun say so early hor u c already then say
4	nah i dont think he goes to usf he lives around here though
5	freemsg hey there darling its been 3 weeks now and no word back id like some fun you up for it still tb ok xxx std chgs to send 150 to rcv
6	even my brother is not like to speak with me they treat me like aids patent
7	as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press 9 to copy your friends callertune
8	winner as a valued network customer you have been selected to receivea 900 prize reward to claim call 09061701461 claim code kl341 valid 12 hours only
9	had your mobile 11 months or more u r entitled to update to the latest colour 

### Expected results:

```
0	go until jurong point  crazy   available only in bugis n great world la e buffet    cine there got amore wat
1	ok lar    joking wif u oni
2	free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005  text fa to 87121 to receive entry question std txt rate t c s apply 08452810075over18 s
3	u dun say so early hor    u c already then say
4	nah i don t think he goes to usf  he lives around here though
5	freemsg hey there darling it s been 3 week s now and no word back  i d like some fun you up for it still  tb ok  xxx std chgs to send   1 50 to rcv
6	even my brother is not like to speak with me  they treat me like aids patent
7	as per your request  melle melle  oru minnaminunginte nurungu vettam   has been set as your callertune for all callers  press  9 to copy your friends callertune
8	winner   as a valued network customer you have been selected to receivea  900 prize reward  to claim call 09061701461  claim code kl341  valid 12 hours only
9	had your mobile 11 months or more  u r entitled to update to the latest colour mobiles with camera for free  call the mobile update co free on 08002986030
10	i m gonna be home soon and i don t want to talk about this stuff anymore tonight  k  i ve cried enough today
11	six chances to win cash  from 100 to 20 000 pounds txt  csh11 and send to 87575  cost 150p day  6days  16  tsandcs apply reply hl 4 info
12	urgent  you have won a 1 week free membership in our  100 000 prize jackpot  txt the word  claim to no  81010 t c www dbuk net lccltd pobox 4403ldnw1a7rw18
13	i ve been searching for the right words to thank you for this breather  i promise i wont take your help for granted and will fulfil my promise  you have been wonderful and a blessing at all times
14	i have a date on sunday with will
15	xxxmobilemovieclub  to use your credit  click the wap link in the next txt message or click here   http   wap  xxxmobilemovieclub com n qjkgighjjgcbl
16	oh k   i m watching here
17	eh u remember how 2 spell his name    yes i did  he v naughty make until i v wet
18	fine if that s the way u feel  that s the way its gota b
19	england v macedonia   dont miss the goals team news  txt ur national team to 87077 eg england to 87077 try wales  scotland 4txt ú1 20 poboxox36504w45wq 16
```

4. As can be seen from the above text, there are many consistent spaces between words, please implement the function `` delete_whitespaces () ``, which will replace all consistent gaps with one gap.

In [8]:
def delete_whitespaces(x):
    #Начало вашего кода
     return re.sub(r'\s+', ' ', str(x)).strip()
    #Конец вашего кода

clean_data["message"] = clean_data["message"].apply(delete_whitespaces)

for i in range(len(clean_data)):
    print(f"{i}\t{clean_data['message'][i]}")

0	go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat
1	ok lar joking wif u oni
2	free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s
3	u dun say so early hor u c already then say
4	nah i dont think he goes to usf he lives around here though
5	freemsg hey there darling its been 3 weeks now and no word back id like some fun you up for it still tb ok xxx std chgs to send 150 to rcv
6	even my brother is not like to speak with me they treat me like aids patent
7	as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press 9 to copy your friends callertune
8	winner as a valued network customer you have been selected to receivea 900 prize reward to claim call 09061701461 claim code kl341 valid 12 hours only
9	had your mobile 11 months or more u r entitled to update to the latest colour 

### Expected results:

```
0	go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat
1	ok lar joking wif u oni
2	free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry question std txt rate t c s apply 08452810075over18 s
3	u dun say so early hor u c already then say
4	nah i don t think he goes to usf he lives around here though
5	freemsg hey there darling it s been 3 week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send 1 50 to rcv
6	even my brother is not like to speak with me they treat me like aids patent
7	as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press 9 to copy your friends callertune
8	winner as a valued network customer you have been selected to receivea 900 prize reward to claim call 09061701461 claim code kl341 valid 12 hours only
9	had your mobile 11 months or more u r entitled to update to the latest colour mobiles with camera for free call the mobile update co free on 08002986030
10	i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today
11	six chances to win cash from 100 to 20 000 pounds txt csh11 and send to 87575 cost 150p day 6days 16 tsandcs apply reply hl 4 info
12	urgent you have won a 1 week free membership in our 100 000 prize jackpot txt the word claim to no 81010 t c www dbuk net lccltd pobox 4403ldnw1a7rw18
13	i ve been searching for the right words to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all times
14	i have a date on sunday with will
15	xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl
16	oh k i m watching here
17	eh u remember how 2 spell his name yes i did he v naughty make until i v wet
18	fine if that s the way u feel that s the way its gota b
19	england v macedonia dont miss the goals team news txt ur national team to 87077 eg england to 87077 try wales scotland 4txt ú1 20 poboxox36504w45wq 16
```

5. Implement the function `` get_vocab (Data, Condition = None) `` `, which accepts one positional argument` `DATA``` (PANDAS.DATAFRAME) and one nominal argument` `` control````. This function should return the dictionary of words and their quantities in `` `Data`` 'relative to the argument` `` condition````.

Example:

* When `` `Condition =" HAM "` ``, the function should return the dictionary of words and their number only in `` `spam`` 'messages.

* When `` `Condition =" Spam "` ``, the function should return the dictionary of words and their number only in `` HAM`` 'messages.

* When `` `Condition = None``` ', the function should return the dictionary of words and their number only in all messages.

In [59]:
def get_vocab(data, condition=None):
    #Начало вашего кода
    if condition is None:
        filtered = data
    else:
        filtered = data[data['status'].str.lower() == condition.lower()]


    all_words = []
    for message in filtered['message']:

        words = message.lower().split()
        all_words.extend(words)

    vocab_series = pd.Series(all_words).value_counts()
    vocab = vocab_series.to_dict()

    return vocab
    #Конец вашего кода

ham_vocab = get_vocab(clean_data,condition="ham")
spam_vocab = get_vocab(clean_data,condition="spam")
vocab = get_vocab(clean_data)

print(ham_vocab,end="\n\n")
print(spam_vocab,end="\n\n")
print(vocab,end="\n\n")

{'i': 7, 'u': 5, 'to': 5, 'your': 4, 'for': 4, 'and': 3, 'been': 3, 'he': 3, 'the': 3, 'until': 2, 'say': 2, 'melle': 2, 'as': 2, 'with': 2, 'me': 2, 'like': 2, 'all': 2, 'callertune': 2, 'will': 2, 'promise': 2, 'a': 2, 'thats': 2, 'way': 2, 'v': 2, 'have': 2, 'you': 2, 'my': 2, 'here': 2, 'this': 2, 'ive': 2, 'dont': 2, 'go': 1, 'cine': 1, 'buffet': 1, 'e': 1, 'la': 1, 'world': 1, 'great': 1, 'n': 1, 'bugis': 1, 'in': 1, 'only': 1, 'available': 1, 'crazy': 1, 'point': 1, 'jurong': 1, 'c': 1, 'hor': 1, 'even': 1, 'though': 1, 'lives': 1, 'around': 1, 'usf': 1, 'then': 1, 'think': 1, 'goes': 1, 'already': 1, 'nah': 1, 'is': 1, 'treat': 1, 'they': 1, 'speak': 1, 'not': 1, 'brother': 1, 'request': 1, 'per': 1, 'aids': 1, 'patent': 1, 'dun': 1, 'oni': 1, 'early': 1, 'so': 1, 'wif': 1, 'joking': 1, 'there': 1, 'got': 1, 'ok': 1, 'lar': 1, 'amore': 1, 'wat': 1, 'im': 1, 'friends': 1, 'copy': 1, '9': 1, 'press': 1, 'callers': 1, 'has': 1, 'set': 1, 'minnaminunginte': 1, 'oru': 1, 'nurungu': 

### Expected results:

```
{'go': 1, 'until': 2, 'jurong': 1, 'point': 1, 'crazy': 1, 'available': 1, 'only': 1, 'in': 1, 'bugis': 1, 'n': 1, 'great': 1, 'world': 1, 'la': 1, 'e': 1, 'buffet': 1, 'cine': 1, 'there': 1, 'got': 1, 'amore': 1, 'wat': 1, 'ok': 1, 'lar': 1, 'joking': 1, 'wif': 1, 'u': 5, 'oni': 1, 'dun': 1, 'say': 2, 'so': 1, 'early': 1, 'hor': 1, 'c': 1, 'already': 1, 'then': 1, 'nah': 1, 'i': 11, 'don': 2, 't': 2, 'think': 1, 'he': 3, 'goes': 1, 'to': 5, 'usf': 1, 'lives': 1, 'around': 1, 'here': 2, 'though': 1, 'even': 1, 'my': 2, 'brother': 1, 'is': 1, 'not': 1, 'like': 2, 'speak': 1, 'with': 2, 'me': 2, 'they': 1, 'treat': 1, 'aids': 1, 'patent': 1, 'as': 2, 'per': 1, 'your': 4, 'request': 1, 'melle': 2, 'oru': 1, 'minnaminunginte': 1, 'nurungu': 1, 'vettam': 1, 'has': 1, 'been': 3, 'set': 1, 'callertune': 2, 'for': 4, 'all': 2, 'callers': 1, 'press': 1, '9': 1, 'copy': 1, 'friends': 1, 'm': 2, 'gonna': 1, 'be': 1, 'home': 1, 'soon': 1, 'and': 3, 'want': 1, 'talk': 1, 'about': 1, 'this': 2, 'stuff': 1, 'anymore': 1, 'tonight': 1, 'k': 2, 've': 2, 'cried': 1, 'enough': 1, 'today': 1, 'searching': 1, 'the': 3, 'right': 1, 'words': 1, 'thank': 1, 'you': 2, 'breather': 1, 'promise': 2, 'wont': 1, 'take': 1, 'help': 1, 'granted': 1, 'will': 2, 'fulfil': 1, 'have': 2, 'wonderful': 1, 'a': 2, 'blessing': 1, 'at': 1, 'times': 1, 'date': 1, 'on': 1, 'sunday': 1, 'oh': 1, 'watching': 1, 'eh': 1, 'remember': 1, 'how': 1, '2': 1, 'spell': 1, 'his': 1, 'name': 1, 'yes': 1, 'did': 1, 'v': 2, 'naughty': 1, 'make': 1, 'wet': 1, 'fine': 1, 'if': 1, 'that': 2, 's': 2, 'way': 2, 'feel': 1, 'its': 1, 'gota': 1, 'b': 1}

{'go': 1, 'until': 2, 'jurong': 1, 'point': 1, 'crazy': 1, 'available': 1, 'only': 1, 'in': 1, 'bugis': 1, 'n': 1, 'great': 1, 'world': 1, 'la': 1, 'e': 1, 'buffet': 1, 'cine': 1, 'there': 1, 'got': 1, 'amore': 1, 'wat': 1, 'ok': 1, 'lar': 1, 'joking': 1, 'wif': 1, 'u': 5, 'oni': 1, 'dun': 1, 'say': 2, 'so': 1, 'early': 1, 'hor': 1, 'c': 1, 'already': 1, 'then': 1, 'nah': 1, 'i': 11, 'don': 2, 't': 2, 'think': 1, 'he': 3, 'goes': 1, 'to': 5, 'usf': 1, 'lives': 1, 'around': 1, 'here': 2, 'though': 1, 'even': 1, 'my': 2, 'brother': 1, 'is': 1, 'not': 1, 'like': 2, 'speak': 1, 'with': 2, 'me': 2, 'they': 1, 'treat': 1, 'aids': 1, 'patent': 1, 'as': 2, 'per': 1, 'your': 4, 'request': 1, 'melle': 2, 'oru': 1, 'minnaminunginte': 1, 'nurungu': 1, 'vettam': 1, 'has': 1, 'been': 3, 'set': 1, 'callertune': 2, 'for': 4, 'all': 2, 'callers': 1, 'press': 1, '9': 1, 'copy': 1, 'friends': 1, 'm': 2, 'gonna': 1, 'be': 1, 'home': 1, 'soon': 1, 'and': 3, 'want': 1, 'talk': 1, 'about': 1, 'this': 2, 'stuff': 1, 'anymore': 1, 'tonight': 1, 'k': 2, 've': 2, 'cried': 1, 'enough': 1, 'today': 1, 'searching': 1, 'the': 3, 'right': 1, 'words': 1, 'thank': 1, 'you': 2, 'breather': 1, 'promise': 2, 'wont': 1, 'take': 1, 'help': 1, 'granted': 1, 'will': 2, 'fulfil': 1, 'have': 2, 'wonderful': 1, 'a': 2, 'blessing': 1, 'at': 1, 'times': 1, 'date': 1, 'on': 1, 'sunday': 1, 'oh': 1, 'watching': 1, 'eh': 1, 'remember': 1, 'how': 1, '2': 1, 'spell': 1, 'his': 1, 'name': 1, 'yes': 1, 'did': 1, 'v': 2, 'naughty': 1, 'make': 1, 'wet': 1, 'fine': 1, 'if': 1, 'that': 2, 's': 2, 'way': 2, 'feel': 1, 'its': 1, 'gota': 1, 'b': 1}

{'go': 1, 'until': 2, 'jurong': 1, 'point': 1, 'crazy': 1, 'available': 1, 'only': 2, 'in': 4, 'bugis': 1, 'n': 2, 'great': 1, 'world': 1, 'la': 1, 'e': 1, 'buffet': 1, 'cine': 1, 'there': 2, 'got': 1, 'amore': 1, 'wat': 1, 'ok': 2, 'lar': 1, 'joking': 1, 'wif': 1, 'u': 6, 'oni': 1, 'free': 4, 'entry': 2, '2': 2, 'a': 5, 'wkly': 1, 'comp': 1, 'to': 21, 'win': 2, 'fa': 2, 'cup': 1, 'final': 1, 'tkts': 1, '21st': 1, 'may': 1, '2005': 1, 'text': 1, '87121': 1, 'receive': 1, 'question': 1, 'std': 2, 'txt': 5, 'rate': 1, 't': 4, 'c': 3, 's': 6, 'apply': 2, '08452810075over18': 1, 'dun': 1, 'say': 2, 'so': 1, 'early': 1, 'hor': 1, 'already': 1, 'then': 1, 'nah': 1, 'i': 12, 'don': 2, 'think': 1, 'he': 3, 'goes': 1, 'usf': 1, 'lives': 1, 'around': 1, 'here': 3, 'though': 1, 'freemsg': 1, 'hey': 1, 'darling': 1, 'it': 2, 'been': 5, '3': 1, 'week': 2, 'now': 1, 'and': 5, 'no': 2, 'word': 2, 'back': 1, 'd': 1, 'like': 3, 'some': 1, 'fun': 1, 'you': 5, 'up': 1, 'for': 6, 'still': 1, 'tb': 1, 'xxx': 1, 'chgs': 1, 'send': 2, '1': 2, '50': 1, 'rcv': 1, 'even': 1, 'my': 2, 'brother': 1, 'is': 1, 'not': 1, 'speak': 1, 'with': 3, 'me': 2, 'they': 1, 'treat': 1, 'aids': 1, 'patent': 1, 'as': 3, 'per': 1, 'your': 6, 'request': 1, 'melle': 2, 'oru': 1, 'minnaminunginte': 1, 'nurungu': 1, 'vettam': 1, 'has': 1, 'set': 1, 'callertune': 2, 'all': 2, 'callers': 1, 'press': 1, '9': 1, 'copy': 1, 'friends': 1, 'winner': 1, 'valued': 1, 'network': 1, 'customer': 1, 'have': 4, 'selected': 1, 'receivea': 1, '900': 1, 'prize': 2, 'reward': 1, 'claim': 3, 'call': 2, '09061701461': 1, 'code': 1, 'kl341': 1, 'valid': 1, '12': 1, 'hours': 1, 'had': 1, 'mobile': 2, '11': 1, 'months': 1, 'or': 2, 'more': 1, 'r': 1, 'entitled': 1, 'update': 2, 'the': 9, 'latest': 1, 'colour': 1, 'mobiles': 1, 'camera': 1, 'co': 1, 'on': 2, '08002986030': 1, 'm': 2, 'gonna': 1, 'be': 1, 'home': 1, 'soon': 1, 'want': 1, 'talk': 1, 'about': 1, 'this': 2, 'stuff': 1, 'anymore': 1, 'tonight': 1, 'k': 2, 've': 2, 'cried': 1, 'enough': 1, 'today': 1, 'six': 1, 'chances': 1, 'cash': 1, 'from': 1, '100': 2, '20': 2, '000': 2, 'pounds': 1, 'csh11': 1, '87575': 1, 'cost': 1, '150p': 1, 'day': 1, '6days': 1, '16': 2, 'tsandcs': 1, 'reply': 1, 'hl': 1, '4': 1, 'info': 1, 'urgent': 1, 'won': 1, 'membership': 1, 'our': 1, 'jackpot': 1, '81010': 1, 'www': 1, 'dbuk': 1, 'net': 1, 'lccltd': 1, 'pobox': 1, '4403ldnw1a7rw18': 1, 'searching': 1, 'right': 1, 'words': 1, 'thank': 1, 'breather': 1, 'promise': 2, 'wont': 1, 'take': 1, 'help': 1, 'granted': 1, 'will': 2, 'fulfil': 1, 'wonderful': 1, 'blessing': 1, 'at': 1, 'times': 1, 'date': 1, 'sunday': 1, 'xxxmobilemovieclub': 2, 'use': 1, 'credit': 1, 'click': 2, 'wap': 2, 'link': 1, 'next': 1, 'message': 1, 'http': 1, 'com': 1, 'qjkgighjjgcbl': 1, 'oh': 1, 'watching': 1, 'eh': 1, 'remember': 1, 'how': 1, 'spell': 1, 'his': 1, 'name': 1, 'yes': 1, 'did': 1, 'v': 3, 'naughty': 1, 'make': 1, 'wet': 1, 'fine': 1, 'if': 1, 'that': 2, 'way': 2, 'feel': 1, 'its': 1, 'gota': 1, 'b': 1, 'england': 2, 'macedonia': 1, 'dont': 1, 'miss': 1, 'goals': 1, 'team': 2, 'news': 1, 'ur': 1, 'national': 1, '87077': 2, 'eg': 1, 'try': 1, 'wales': 1, 'scotland': 1, '4txt': 1, 'ú1': 1, 'poboxox36504w45wq': 1}
```

6. Now the time has come to calculate the conditional probabilities for each word $ p (spam | (w_1, w_2, ..., w_n)) $ and $ p (Ham | (w_1, w_2, ..., w_n) $. Implement the function `` Calc_Prob (*arg) `` `, the first input argument is either` `spam_vocab````, or` `HAM_VOCAB`````, the second input should be` `` vOCAB``` `` `Message``` - a new message from the user.

In [52]:
import re

def calc_probs(vocab_dict, vocab, message, alpha=1):
    #Начало вашего кода
    total_words = sum(vocab_dict.values())
    V = len(vocab)
    words = re.findall(r'\w+', message.lower())
    prob = 1.0
    for word in words:
        word_count = vocab_dict.get(word, 0)
        prob *= (word_count + alpha) / (total_words + alpha * V)
    return prob
    #Конец вашего кода

message = "WINNER WINNER WINNER WINNER WINNER"

p_ham_given_message = p_ham * calc_probs(ham_vocab, vocab, message, alpha=1)
p_spam_given_message = p_spam * calc_probs(spam_vocab, vocab, message, alpha=1)

print(p_ham_given_message)
print(p_spam_given_message)

condition = "ham"

if p_spam_given_message > p_ham_given_message:
    condition = "spam"
print(condition)

2.6725262832189473e-14
4.869387268319662e-13
spam


### Expected results:

```
2.282525282024841e-14
3.637978807091713e-13
spam
```

7. Implement the function `` Filter_spam (Message, P_Spam, Spam_vocab, P_HAM, HAM_VOCAB, VOCAB, Alpha = 1) `` `, which will check if the incoming message is` `spam``` 'or` `HAM``````.

In [58]:

import re

def filter_spam(message, p_spam, spam_vocab, p_ham, ham_vocab, vocab, alpha=1):
    #Начало вашего кода
    def calc_probability(vocab_dict, vocab, message, alpha=1):
        total_words = sum(vocab_dict.values())
        V = len(vocab)
        words = re.findall(r'\w+', message.lower())

        prob = 1.0
        for word in words:
            word_count = vocab_dict.get(word, 0)
            prob *= (word_count + alpha) / (total_words + alpha * V)

        return prob


    p_message_given_spam = calc_probability(spam_vocab, vocab, message, alpha)
    p_message_given_ham = calc_probability(ham_vocab, vocab, message, alpha)
    p_spam_given_message = p_spam * p_message_given_spam
    p_ham_given_message = p_ham * p_message_given_ham


    if p_spam_given_message > p_ham_given_message:
        return "spam"
    else:
        return "ham"
    #Конец вашего кода



print(filter_spam("Hello, how are you? ", p_spam, spam_vocab, p_ham, ham_vocab, vocab, alpha=1))
print(filter_spam("Congrats! You won 1000000 ", p_spam, spam_vocab, p_ham, ham_vocab, vocab, alpha=1))
print(filter_spam("Winner! Winner! Winner! ", p_spam, spam_vocab, p_ham, ham_vocab, vocab, alpha=1))
print(filter_spam("Urgent! You gor free ticket!", p_spam, spam_vocab, p_ham, ham_vocab, vocab, alpha=1))

ham
spam
spam
spam


### Expected results:

```
ham
spam
spam
spam
```

### Great job